on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.9
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Generate virtual environment from pyptoject.toml
        run: poetry install
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Generate zappa_settings config with Discord secrets
        run: envsubst envsubst < zappa_settings.json.tpl > zappa_settings.json
      - name: Update zappa deployment
        run: zappa update dev
